[package]
name = "chai-reaction"
version = "0.1.0"
authors = ["olekspickle <22867443+olekspickle@users.noreply.github.com>"]
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/olekspickle/chai-reaction"

[features]
default = [ "dev_native" ]
dev = [
    "bevy/bevy_dev_tools",
    "bevy/bevy_ui_debug",
    "bevy/dynamic_linking",         # Improve compile times for dev builds by linking Bevy as a dynamic library.
    "bevy/track_location",          # Improve error messages coming from Bevy
]
dev_native = [
    "dev",
    "bevy/embedded_watcher",        # Enable embedded asset hot reloading for native dev builds.
    "bevy/file_watcher",            # Enable asset hot reloading for native dev builds.
]


[dependencies]
bevy_seedling = "0.4"
# everything except bevy_audio
bevy = { version = "^0.16", default-features = false, features = [
    "std",
    "sysinfo_plugin",
    "multi_threaded",
    "hdr",
    "smaa_luts",
    "tonemapping_luts",
    "bevy_render",
    "bevy_winit",
    "bevy_state",
    "bevy_color",
    "bevy_asset",
    "bevy_core_pipeline",
    "bevy_scene",
    "bevy_picking",
    "bevy_mesh_picking_backend",
    "bevy_text",
    "bevy_ui",
    "bevy_sprite",
    "bevy_sprite_picking_backend",
    "bevy_ui_picking_backend",
    "bevy_input_focus",
    "custom_cursor",
    "default_font",
    "animation",
    "bevy_log",
    "bevy_gilrs",
    "bevy_gizmos",
    "png",
    "jpeg",
    "webgl2",
    "x11",
    "wayland"
] }

# physics
avian2d = { version = "0.3", features = ["2d", "parallel"] }

# key bindings
leafwing-input-manager = "0.17"

# misc
ron = "0.10"
rand = { version = "0.8" }
serde = "1"
image = "0.25.6"
thiserror = "2.0.12"
## This greatly improves WGPU's performance due to its heavy use of trace! calls
log = { version = "0.4", features = ["max_level_debug", "release_max_level_warn"] }
# keep the following in sync with Bevy's dependencies
winit = { version = "0.30", default-features = false }
bevy_fix_gltf_coordinate_system = "0.1.0"
enum-iterator = "2.1.0"
strum = "0.27.1"
strum_macros = "0.27.1"

[lints.clippy]
# Bevy supplies arguments to systems via dependency injection, so it's natural for systems to
# request more than 7 arguments, which would undesirably trigger this lint.
too_many_arguments = "allow"
type_complexity = "allow"           # Queries may access many components, which would undesirably trigger this lint.
nonstandard_macro_braces = "warn"   # Make sure macros use their standard braces, such as `[]` for `bevy_ecs::children!`.

[package.metadata.bevy_cli.release] # Disable dev features for release builds.
default-features = false
[package.metadata.bevy_cli.web]     # Disable native features for web builds.
default-features = false
[package.metadata.bevy_cli.web.dev]
features = ["dev"]

[profile.ci]                # Optimize for build time in CI.
inherits = "dev"
opt-level = 0
debug = "line-tables-only"
codegen-units = 4
[profile.ci.package."*"]
opt-level = 0

[profile.dev]               # Less optimization in the dev profile.
opt-level = 1
[profile.dev.package."*"]   # More optimization in the dev profile for dependencies.
opt-level = 3

[profile.release]
# Do a second optimization pass over the entire program, including dependencies.
# Slows compile times, marginal improvements.
lto = "thin"
# Optimize with size in mind (also try "z", sometimes it is better).
# Slightly slows compile times, great improvements to file size and runtime performance.
opt-level = "s"
codegen-units = 1           # Compile the entire crate as one unit. Slows compile times, marginal improvements.
strip = true


[profile.wasm-release]      # Optimize for size in the wasm-release profile to reduce load times and bandwidth usage on web.
inherits = "release"
strip = "debuginfo"         # Strip all debugging information from the binary to slightly reduce file size.

[build-dependencies]
embed-resource = "1"
